sudo: required
language: node_js
node_js:
  - "9.5.0"
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t storage .
  - docker tag storage $DOCKER_USERNAME/storage:latest
  - docker push $DOCKER_USERNAME/storage:lateste

script:
  - exit 0
